-- MySQL Script generated by MySQL Workbench
-- Qua 11 Mai 2016 08:49:56 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AcademicoWeb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AcademicoWeb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AcademicoWeb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `AcademicoWeb` ;

-- -----------------------------------------------------
-- Table `AcademicoWeb`.`Disciplinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AcademicoWeb`.`Disciplinas` ;

CREATE TABLE IF NOT EXISTS `AcademicoWeb`.`Disciplinas` (
  `disc_codigo` INT NOT NULL COMMENT '',
  `disc_nome` VARCHAR(45) NOT NULL COMMENT '',
  `disc_ementa` VARCHAR(300) NOT NULL COMMENT '',
  PRIMARY KEY (`disc_codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AcademicoWeb`.`Estudantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AcademicoWeb`.`Estudantes` ;

CREATE TABLE IF NOT EXISTS `AcademicoWeb`.`Estudantes` (
  `estu_matricula` VARCHAR(30) NOT NULL COMMENT '',
  `estu_nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`estu_matricula`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AcademicoWeb`.`Cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AcademicoWeb`.`Cursos` ;

CREATE TABLE IF NOT EXISTS `AcademicoWeb`.`Cursos` (
  `curs_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `curs_nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`curs_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AcademicoWeb`.`Professores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AcademicoWeb`.`Professores` ;

CREATE TABLE IF NOT EXISTS `AcademicoWeb`.`Professores` (
  `prof_siape` INT NOT NULL COMMENT '',
  `prof_nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`prof_siape`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AcademicoWeb`.`Responsaveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AcademicoWeb`.`Responsaveis` ;

CREATE TABLE IF NOT EXISTS `AcademicoWeb`.`Responsaveis` (
  `resp_disc_id` INT NOT NULL COMMENT '',
  `resp_prof_siape` INT NOT NULL COMMENT '',
  `resp_ano` VARCHAR(45) NOT NULL COMMENT '',
  `resp_semestre` ENUM('1','2','0') NOT NULL COMMENT '1=primeiro semestre\n2=segundo semestre\n0=matéria não sendo lessionada',
  PRIMARY KEY (`resp_disc_id`, `resp_prof_siape`)  COMMENT '',
  INDEX `fk_Disciplinas_has_Professores_Professores1_idx` (`resp_prof_siape` ASC)  COMMENT '',
  INDEX `fk_Disciplinas_has_Professores_Disciplinas_idx` (`resp_disc_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Disciplinas_has_Professores_Disciplinas`
    FOREIGN KEY (`resp_disc_id`)
    REFERENCES `AcademicoWeb`.`Disciplinas` (`disc_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disciplinas_has_Professores_Professores1`
    FOREIGN KEY (`resp_prof_siape`)
    REFERENCES `AcademicoWeb`.`Professores` (`prof_siape`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AcademicoWeb`.`Matriculas_por_disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AcademicoWeb`.`Matriculas_por_disciplina` ;

CREATE TABLE IF NOT EXISTS `AcademicoWeb`.`Matriculas_por_disciplina` (
  `matrd_estu_matricula` VARCHAR(30) NOT NULL COMMENT '',
  `matrd_disc_codigo` INT NOT NULL COMMENT '',
  `matrd_nota` VARCHAR(45) NOT NULL COMMENT '',
  `matrd_status` ENUM('0','1') NULL COMMENT '0=não aprovado\n1=aprovado',
  `matrd_data_inicial` DATE NOT NULL COMMENT '',
  `matrd_data_final` DATE NULL COMMENT '',
  PRIMARY KEY (`matrd_estu_matricula`, `matrd_disc_codigo`)  COMMENT '',
  INDEX `fk_Matriculas_por_disciplina_Disciplinas1_idx` (`matrd_disc_codigo` ASC)  COMMENT '',
  CONSTRAINT `fk_Matriculas_por_disciplina_Estudantes1`
    FOREIGN KEY (`matrd_estu_matricula`)
    REFERENCES `AcademicoWeb`.`Estudantes` (`estu_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matriculas_por_disciplina_Disciplinas1`
    FOREIGN KEY (`matrd_disc_codigo`)
    REFERENCES `AcademicoWeb`.`Disciplinas` (`disc_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `AcademicoWeb`.`Matriculas_por_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AcademicoWeb`.`Matriculas_por_curso` ;

CREATE TABLE IF NOT EXISTS `AcademicoWeb`.`Matriculas_por_curso` (
  `matrc_estu_matricula` VARCHAR(30) NOT NULL COMMENT '',
  `matrc_curs_id` INT NOT NULL COMMENT '',
  `matrc_data_inicial` DATE NOT NULL COMMENT '',
  `matrc_data_final` DATE NULL COMMENT '',
  INDEX `fk_Matriculas_por_curso_Cursos1_idx` (`matrc_curs_id` ASC)  COMMENT '',
  INDEX `fk_Matriculas_por_curso_Estudantes1_idx` (`matrc_estu_matricula` ASC)  COMMENT '',
  PRIMARY KEY (`matrc_estu_matricula`, `matrc_curs_id`)  COMMENT '',
  CONSTRAINT `fk_Matriculas_por_curso_Cursos1`
    FOREIGN KEY (`matrc_curs_id`)
    REFERENCES `AcademicoWeb`.`Cursos` (`curs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matriculas_por_curso_Estudantes1`
    FOREIGN KEY (`matrc_estu_matricula`)
    REFERENCES `AcademicoWeb`.`Estudantes` (`estu_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `AcademicoWeb`.`Matrizes_de_cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AcademicoWeb`.`Matrizes_de_cursos` ;

CREATE TABLE IF NOT EXISTS `AcademicoWeb`.`Matrizes_de_cursos` (
  `matrz_curs_id` INT NOT NULL COMMENT '',
  `matrz_disc_codigo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`matrz_curs_id`, `matrz_disc_codigo`)  COMMENT '',
  INDEX `fk_Cursos_has_Disciplinas_Disciplinas1_idx` (`matrz_disc_codigo` ASC)  COMMENT '',
  INDEX `fk_Cursos_has_Disciplinas_Cursos1_idx` (`matrz_curs_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Cursos_has_Disciplinas_Cursos1`
    FOREIGN KEY (`matrz_curs_id`)
    REFERENCES `AcademicoWeb`.`Cursos` (`curs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_has_Disciplinas_Disciplinas1`
    FOREIGN KEY (`matrz_disc_codigo`)
    REFERENCES `AcademicoWeb`.`Disciplinas` (`disc_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
